import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[scrolling]
history = 100000

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"
